# Generated by Django 5.2.16 on 2026-09-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Оригинальное изображение"
                    ),
                ),
                (
                    "optimized_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="optimized/%Y/%m/%d/",
                        verbose_name="Оптимизированное изображение",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/%Y/%m/%d/",
                        verbose_name="Миниатюра",
                    ),
                ),
                (
                    "optimized_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "optimized_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "thumbnail_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "thumbnail_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="SHA-256 оригинала",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Альтернативный текст (для SEO и доступности)",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Заголовок/Описание"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
                ),
            ],
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
                "ordering": ["-uploaded_at", "-id"],
                "indexes": [
                    models.Index(fields=["-uploaded_at", "-id"], name="gallery_photo_up_id_idx")
                ],
            },
        ),
    ]
