# Generated by Django 5.2.17 on 2026-09-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="medium_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="medium_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="medium/%Y/%m/%d/", verbose_name="Средняя версия"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="medium_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
