# Generated by Django 6.1.1 on 2026-09-30 18:11

from django.db import migrations, models

import gallery.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_photo_medium_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                upload_to=gallery.models.original_upload_to,
                verbose_name="Оригинальное изображение",
            ),
        ),
    ]
