# Generated by Django 6.1.1 on 2026-09-30 18:28

from django.db import migrations, models


def number_by_upload_date(apps, schema_editor):
    """Существующая лента сохраняет свой порядок: новые сверху, как и раньше."""
    Photo = apps.get_model("gallery", "Photo")
    photos = list(Photo.objects.order_by("-uploaded_at", "-id").only("id"))
    for index, photo in enumerate(photos):
        photo.position = index
    Photo.objects.bulk_update(photos, ["position"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_photo_random_original_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["position", "-id"],
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
            },
        ),
        migrations.RemoveIndex(
            model_name="photo",
            name="gallery_photo_up_id_idx",
        ),
        migrations.AddField(
            model_name="photo",
            name="position",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.RunPython(number_by_upload_date, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["position", "-id"], name="gallery_photo_pos_id_idx"),
        ),
    ]
