# Generated by Django 5.2.16 on 2026-07-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_photo_gallery_photo_up_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="optimized_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="optimized_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
