# Generated by Django 5.2.16 on 2026-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_backfill_variant_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="content_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="SHA-256 оригинала",
            ),
        ),
    ]
