# Generated by Django 5.2.16 on 2026-09-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0009_backfill_content_hash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["-uploaded_at", "-id"],
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
            },
        ),
        migrations.RemoveIndex(
            model_name="photo",
            name="gallery_photo_up_idx",
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["-uploaded_at", "-id"], name="gallery_photo_up_id_idx"),
        ),
    ]
